ppw/urls.py
from django.urls import path, include
from .views import *

app_name = 'ppw'

urlpatterns = [
    path('', home, name='home'),
    path('story3', index, name='story3'),
    path('story3more', story, name='story3more')
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw.urls')),
]

ppw/models.py
from django.db import models

# Create your models here.

ppw/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home.html')

def index(request):
    return render(request, 'index.html')

def story(request):
    return render(request, 'story.html')

ppw/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}{% endblock title %}
    </head>

    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

ppw/templates/home.html
{% extends "base.html" %}
{% load static %}

    {% block title %}
        <title>Fauzan "Corfaitch" Hanandito</title>
        <link rel="stylesheet" href="{% static 'CSS/main.css' %}">
    {% endblock title %}


    {% block content %}
        <div class="grid-container-1">
            <div class="grid-item-1">
                <img src="{% static 'Assets/Dito.jpg' %}" width="600" height="600">
            </div>
            <div class="grid-item-2">
                <ul>
                    <h1>Fauzan Hanandito</h1>
                    <h3>(Also known as Corfaitch)</h3>
                    <h3>Student ID: 1906426815</h3>
                    <h3>Batch: 2019</h3>
                    <h3>Major: computer science</h3>
                    <h2>UI Student, UI/UX enthusiast, humor-covered</h2>
                </ul>
                
            </div>
        </div>
        <div class="grid-container-2">
            <h2 class="description-text">My description</h2>
            <ul class="list-of-description">
                <li class="list-of-description-bullet">Highly self-aware</li>
                <li class="list-of-description-bullet">Creative</li>
                <li class="list-of-description-bullet">Critical</li>
                <li class="list-of-description-bullet">Sometimes love inserting bite-size humor</li>
            </ul>
        </div>
        <div class="grid-container-3">
            <h2 class="my-social-media">My social media</h2>
            <ul class="social-media">
                <li class="social-media-list">
                    <a href="https://www.instagram.com/corfaitch" title="My Instagram"><img src="{% static 'Assets/instagram-512.png' %}" width="300" height="300"></a>
                </li>
                <li class="social-media-list">
                    <a href="https://twitter.com/corfaitch" title="My Twitter"><img src="{% static 'Assets/twitter-512.png' %}" width="300" height="300"></a>
                </li>
                <li class="social-media-list">
                    <a href="https://steamcommunity.com/id/Corfaitch" title="My Steam"><img src="{% static 'Assets/steam-512.png' %}" width="300" height="300"></a>
                </li>
            </ul>
        </div>
    {% endblock content %}

ppw/templates/index.html
{% extends "base.html" %}
{% load static %}
    {% block title %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fauzan "Corfaitch" Hanandito</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">   
    <link rel="stylesheet" href="{% static 'CSS/main2.css' %}">
    {% endblock title %}


    {% block content %}
        <div class="container-1">
            <div class="row align-items-center">
                <div class=" m-5 col-sm align-items-center">
                    <img src="{% static 'Assets/dito_profile_round.png' %}" alt="profile graphic" class="img-fluid">
                </div>
                <div class="m-5 col-sm">
                    <h1 class="display-1 my-5"><strong>Fauzan "Corfaitch" Hanandito</strong></h1>
                    <h2 class="display-4">Professionally quirky</h2>
                </div>
            </div>
        </div>
        <div class="container-2">
            <h1 class="text-center text-white p-5 display-3">About me</h1>
            <div class="row p-5">
                <div class="col-sm text-center text-white">
                    <img src="{% static 'Assets/mortarboard_white.png' %}" alt="mortarboard white" width="300" height="300" class="m-5">
                    <p class="text-center">"I'm known as a student of Computer Science at Universitas Indonesia, batch 2019, NPM 1906426815"</p>
                </div>
                <div class="col-sm text-center text-white">
                    <img src="{% static 'Assets/joystick_white.png' %}" alt="joystick white" width="300" height="300" class="m-5">
                    <p class="text-center">"I also want to be a game developer, currently working on a horror game."</p>
                </div>
                <div class="col-sm text-center text-white">
                    <img src="{% static 'Assets/bed_white.png' %}" alt="bed white" width="300" height="300" class="m-5">
                    <p class="text-center">"I only sleep 4 hours a day."</p>
                </div>
            </div>
        </div>
        <div class="container-3">
            <h2 class="text-center text-white p-5 display-3">My social media</h2>
            <div class="row p-5">
                <div class="col-sm text-center text-white">
                    <a href="https://www.instagram.com/corfaitch" title="My Instagram."><img src="{% static 'Assets/instagram_white.png' %}" alt="instagram blue" width="300" height="300" class="m-5"></a>
                    <p class="text-center">Face reveal collection is here.</p>
                </div>
                <div class="col-sm text-center text-white">
                    <a href="https://twitter.com/Corfaitch" title="My Twitter."><img src="{% static 'Assets/twitter_white.png' %}" alt="twitter blue" width="300" height="300" class="m-5"></a>
                    <p class="text-center">I rarely use it.</p>
                </div>
                <div class="col-sm text-center text-white">
                    <a href="https://steamcommunity.com/id/corfaitch" title="My Steam."><img src="{% static 'Assets/steam_white.png' %}" alt="steam blue" width="300" height="300" class="m-5"></a>
                    <p class="text-center">Looking for that lucrative discount from GabeN.</p>
                </div>
            </div>
        </div>
        <div class="container-4 p-5 "> 
            <h2 class="text-center p-5 display-4">More about me here</h2>
            <h3 class="text-center p-5"><a href="{% url 'ppw:story3more' %}" title="My story">Learn more</a></h3>
        </div>
        <div class="container-5">
            <p class="text-center text-white p-5">Icons made by
                <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a>,
                <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a>, and
                <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> with some color changes.
                <br/>
                Ⓒ Corfaitch 2021
            </p>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock content %}

ppw/templates/story.html
{% extends "base.html" %}
{% load static %}
    {% block title %}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Fauzan "Corfaitch" Hanandito</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">   
        <link rel="stylesheet" href="{% static 'CSS/main2.css' %}">
    {% endblock title %}


    {% block content %}
        <div class="container-1">
            <div class="align-items-center p-5">
                <h1 class="text-center display-1 p-5">My story so far...</h1>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                    <h1 class="text-white px-5 display-3">1998</h1>
                    <h3 class="text-white p-5 display-4">Born in Balikpapan.</h3>
                </div>
                <div class="col p-5">
                <div>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                </div>
                <div class="col p-5">
                <div>
                    <h1 class="text-white px-5 display-3">2000</h1>
                    <h3 class="text-white p-5 display-4">Got my first PS1.</h3>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                    <h1 class="text-white px-5 display-3">2002</h1>
                    <h3 class="text-white p-5 display-4">Entered my first kindergarden.</h3>
                </div>
                <div class="col p-5">
                <div>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                </div>
                <div class="col p-5">
                <div>
                    <h1 class="text-white px-5 display-3">2005</h1>
                    <h3 class="text-white p-5 display-4">Graduate from kindergarden</h3>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                    <h1 class="text-white px-5 display-3">2009</h1>
                    <h3 class="text-white p-5 display-4">Won my first medal at international mathematics competition.</h3>
                </div>
                <div class="col p-5">
                <div>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                </div>
                <div class="col p-5">
                <div>
                    <h1 class="text-white px-5 display-3">2011</h1>
                    <h3 class="text-white p-5 display-4">Graduated from elementary school.</h3>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                    <h1 class="text-white px-5 display-3">2014</h1>
                    <h3 class="text-white p-5 display-4">Graduated from middle school.</h3>
                </div>
                <div class="col p-5">
                <div>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                </div>
                <div class="col p-5">
                <div>
                    <h1 class="text-white px-5 display-3">2017</h1>
                    <h3 class="text-white p-5 display-4">Graduated from high school.</h3>
                </div>
            </div>
        </div>
        <div class="container-2">
        </br class="p-5">
            <div class="row p-5">
                <div class="col p-5">
                    <h1 class="text-white px-5 display-3">2019</h1>
                    <h3 class="text-white p-5 display-4">Entered Universitas Indonesia.</h3>
                </div>
                <div class="col p-5">
                <div>
                </div>
            </div>
        </div>
        </br class="p-5">
        <div class="container-2 p-5">
            <h1 class="text-white text-center p-5 display-2">And the story continues...</h1>
        </div>
        <div class="container-4 p-5">
        </br class="p-5">
            <h1 class="text-center p-5 display-2">Go back to the main page</h1>
            </br class="p-5">
            </br class="p-5">
            <h3 class="text-center p-5"><a href="{% url 'ppw:story3' %}" title="Go back">Go back</a></h3>
        </br class="p-5">
        </div>
        <div class="container-5">
            <p class="text-center text-white p-5">Icons made by
                <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a>,
                <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a>, and
                <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> with some color changes.
                <br/>
                Ⓒ Corfaitch 2021
            </p>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock content %}